name: Repository Hygiene

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  hygiene-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check README
        run: |
          if [ ! -f README.md ]; then
            echo "README.md is missing"
            exit 1
          fi

      - name: Check LICENSE
        run: |
          if [ ! -f LICENSE ]; then
            echo "LICENSE file is missing"
            exit 1
          fi
